name: "Build"

on: [pull_request]

jobs:
  run-tests:
    name: "Run Tests"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12", "3.13", "3.14"]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Ensure browsers are installed
        run: python -m playwright install

      - name: Run tests
        run: pytest

      - name: Set artifact name
        id: artifact
        shell: bash
        run: echo "name=result-output-${{ matrix.os }}-python-$(echo '${{ matrix.python-version }}' | tr '.' '_')" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ !cancelled() }}
        with:
          name: ${{ steps.artifact.outputs.name }}
          path: ${{ github.workspace }}/axe-reports/
          retention-days: 5
